#!/bin/bash

bundle exec rake generate
./tagify.pl --dir .
bundle exec rake generate

find /Users/aijaz/octopress/public \
     -type f \
     -name '*.html' \
     -exec /Users/aijaz/octopress/imageCaption.pl '{}' ';'

